import {
  FiZap,
  FiDroplet,
  FiWind,
  FiHome,
  FiTool,
  FiMonitor,
  FiScissors,
  FiSettings,
} from "react-icons/fi";

const servicesData = [
  {
    id: 1,
    title: "Electrician",
    icon: FiZap,
    category: "Electrical",
    rating: 4.9,
    reviews: 1234,
    price: "₹299",
    duration: "30 mins",
    description: "Professional electrical installation and repair services.",
  },
  {
    id: 2,
    title: "Plumber",
    icon: FiDroplet,
    category: "Plumbing",
    rating: 4.8,
    reviews: 982,
    price: "₹249",
    duration: "35 mins",
    description: "Leak repairs, pipe fitting and bathroom maintenance.",
  },
  {
    id: 3,
    title: "AC Repair",
    icon: FiWind,
    category: "AC",
    rating: 4.9,
    reviews: 765,
    price: "₹599",
    duration: "45 mins",
    description: "AC installation, servicing and gas refilling.",
  },
  {
    id: 4,
    title: "Home Cleaning",
    icon: FiHome,
    category: "Cleaning",
    rating: 4.8,
    reviews: 1567,
    price: "₹499",
    duration: "2 hrs",
    description: "Deep cleaning for home, kitchen and bathrooms.",
  },
  {
    id: 5,
    title: "Carpenter",
    icon: FiTool,
    category: "Furniture",
    rating: 4.7,
    reviews: 543,
    price: "₹399",
    duration: "1 hr",
    description: "Furniture repair, installation and wood work.",
  },
  {
    id: 6,
    title: "Appliance Repair",
    icon: FiMonitor,
    category: "Appliance",
    rating: 4.9,
    reviews: 689,
    price: "₹349",
    duration: "50 mins",
    description: "TV, refrigerator and washing machine repairs.",
  },
  {
    id: 7,
    title: "Salon at Home",
    icon: FiScissors,
    category: "Salon",
    rating: 4.9,
    reviews: 1120,
    price: "₹699",
    duration: "60 mins",
    description: "Professional beauty and grooming services at home.",
  },
  {
    id: 8,
    title: "Appliance Installation",
    icon: FiSettings,
    category: "Installation",
    rating: 4.8,
    reviews: 432,
    price: "₹399",
    duration: "40 mins",
    description: "Safe installation of all household appliances.",
  },
];

export default servicesData;